language: python
python:
    - "3.5"
    - "3.6"
before_script:
  - pip install git+git://github.com/ellisonleao/vl.git@py3
  - vl --version
script:
  - vl README.md --debug -w linkedin.com,jumpy.com.br,pegcar.com -a 503,405,401,403,301
